### ISSUE TITLE
virtualenv_create error

### ISSUE THREAD

**Issue by r1sh4bh** [ranikay/shiny-reticulate-app#5]
Thank you for the amazing tutorial. 

When I try running it locally, the app opens for a fraction of a second and then the closes down. But the console still shows the Busy sign and the following error :
`Listening on http://127.0.0.1:7450
Warning: Error in system2: '"python3"' not found
  53: system2
  52: python_version
  51: virtualenv_module
  50: reticulate::virtualenv_create
  49: server [C:\Hackathon/app.R#164]
Error in system2(python, args, stdout = TRUE, stderr = FALSE) : 
  '"python3"' not found`

When I deploy it on shinyapps.io, the deployment is complete, but the its blocked out and gives the error `Disconnected from the server`. I checked the logs and the logs show a similar error:
 `62: reticulate::virtualenv_create
Error in system2(python, args, stdout = TRUE, stderr = FALSE) : 
65: system2
error in running command`

i tried getting the python config and I see its missing the virtual environment altogether:
`> reticulate::py_config()
python:         C:/Users/risha/AppData/Local/r-miniconda/envs/r-reticulate/python.exe
libpython:      C:/Users/risha/AppData/Local/r-miniconda/envs/r-reticulate/python36.dll
pythonhome:     C:/Users/risha/AppData/Local/r-miniconda/envs/r-reticulate
version:        3.6.10 (default, Mar  5 2020, 10:17:47) [MSC v.1900 64 bit (AMD64)]
Architecture:   64bit
numpy:          C:/Users/risha/AppData/Local/r-miniconda/envs/r-reticulate/Lib/site-packages/numpy
numpy_version:  1.18.1`

Could you help solving this please. Thank you!

**Comment by ranikay** [comment]
Hi Rishabh, thanks for the comment. As it's written, this app is configured to create a `virtualenv` virtual environment using the system Python 3 when running locally. It looks like your default Python 3 was installed with miniconda, so it would live on a different path. In the command prompt, if you type `python` and press Enter, what is the path to Python shown?

I'm not sure if it's possible to create a `virtualenv` virtual environment using a miniconda Python path. To test this, you could replace the "python3" on line 28 of the .Rprofile file with the python path output by your command prompt and see if it works.

Alternatively, you could create a `conda` virtual environment using `reticulate::conda_create()` instead of `reticulate::virtualenv_create()` but note that [conda is not supported on shinyapps.io](https://community.rstudio.com/t/how-to-use-conda-environment-in-shinyapps-io/18630) so it sounds like that may not be ideal for you.
